const BRAND_COLOR_PRIMARY = import.meta.env.VITE_APP_ORDERCLOUD_BRAND_COLOR_PRIMARY || ''
const BRAND_COLOR_SECONDARY = import.meta.env.VITE_APP_ORDERCLOUD_BRAND_COLOR_SECONDARY || ''
const BRAND_COLOR_ACCENT = import.meta.env.VITE_APP_ORDERCLOUD_BRAND_COLOR_ACCENT || ''

const BRAND_LOGO_LIGHT = import.meta.env.VITE_APP_ORDERCLOUD_BRAND_LOGO_LIGHT || ''
const BRAND_LOGO_DARK = import.meta.env.VITE_APP_ORDERCLOUD_BRAND_LOGO_DARK || ''
const BRAND_FAVICON_LIGHT = import.meta.env.VITE_APP_ORDERCLOUD_BRAND_LOGO_LIGHT || ''
const BRAND_FAVICON_DARK = import.meta.env.VITE_APP_ORDERCLOUD_BRAND_LOGO_DARK || ''

export {
  BRAND_COLOR_PRIMARY,
  BRAND_COLOR_SECONDARY,
  BRAND_COLOR_ACCENT,
  BRAND_LOGO_LIGHT,
  BRAND_LOGO_DARK,
  BRAND_FAVICON_LIGHT,
  BRAND_FAVICON_DARK,
}
