enum PAYMENT_PROVIDERS {
  CARD_CONNECT,
  PAYPAL,
  STRIPE,
  BLUESNAP,
}

const PAYMENT_PROVIDER = import.meta.env.VITE_APP_PAYMENT_PROVIDER as PAYMENT_PROVIDERS

export { PAYMENT_PROVIDER, PAYMENT_PROVIDERS }
